FROM ghcr.io/astral-sh/uv:python3.13-bookworm-slim

ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy

WORKDIR /app

RUN apt update && apt upgrade
RUN apt install ffmpeg -y

RUN --mount=type=cache,target=/root/.cache/uv \
    uvx playwright install --with-deps chromium

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    --mount=type=bind,source=vendored/,target=vendored/ \
    uv sync --frozen --no-install-project --no-dev --all-extras

ENV PATH="/app/.venv/bin:$PATH"

COPY pyproject.toml main.py uv.lock ./
COPY src ./src

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=vendored/,target=vendored/ \
    uv sync --frozen --no-dev --all-extras

# Reset the entrypoint, don't invoke `uv`
ENTRYPOINT []

CMD ["fastapi", "dev", "--host", "0.0.0.0"]